# Site settings
author: Merkeresseria Coleman
title: Merkeresseria Coleman
header-img: img/home-bg.png
email: kttsmllc@gmail.com
copyright_name: Merkeresseria Coleman
description: > # this means to ignore newlines until "baseurl:"
  Facts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Keilyn92

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
